### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by decenergy** [vanatteveldt/rsyntax#1]
Installing package rsyntax results in the following error message:

```
> library(devtools)
> install_github("vanatteveldt/rsyntax/R")
Downloading GitHub repo vanatteveldt/rsyntax@master
Error in utils::unzip(src, exdir = target) : 
  cannot open file 'C:/Users/Jeroen/AppData/Local/Temp/RtmpIlQe1l/devtools1ec421715fc2/vanatteveldt-rsyntax-07a1cc9/R/aux.R': No such file or directory
```

Downloading the file and install it locally does not work:

```
> install_local("C:\\Users\\Jeroen\\Downloads\\rsyntax-master.zip")
Error in utils::unzip(src, exdir = target) : 
  cannot open file 'C:/Users/Jeroen/AppData/Local/Temp/RtmpIlQe1l/devtools1ec479697554/rsyntax-master/R/aux.R': No such file or directory
```

R folder at the file location mentioned is indeed empty. How could this be solved?

**Comment by vanatteveldt** [comment]
Annoying, it installs fine for me. 

Could you try running R as administrator on Windows?

@kasperwelbers, do you have any idea?

**Comment by vanatteveldt** [comment]
note that the install syntax should be:

```
# edit: install_github("vanatteveldt/rsyntax/R") # this is wrong!
install_github("vanatteveldt/rsyntax")
```

Does that work?

**Comment by decenergy** [comment]
I tried that already. Leads to the same problem. Somehow I am unable to unzip aux.R even if I do it manually. It just tells me the file is not there. The three other files within the folder (clauses,r , data.r and rsyntax.r) can be unzipped though...

**Comment by kasperwelbers** [comment]
To be sure, it should be without /R

So:
install_github('vanatteveldt/rsyntax')

Does that work?

2015-12-14 17:17 GMT+01:00 Wouter van Atteveldt notifications@github.com:

> note that the install syntax should be:
> 
> install_github("vanatteveldt/rsyntax/R")
> 
> Does that work?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vanatteveldt/rsyntax/issues/1#issuecomment-164481772.

## 

Postdoctoral researcher
Department of Communication Science
Faculty of Social Sciences, VU University Amsterdam

De Boelelaan 1081,
1081 HV Amsterdam, the Netherlands
Room Z-429 Metropolitan Building

**Comment by decenergy** [comment]
Yes, tried this too. It is some kind of windows problem I suppose. Unzipping that one specific file does not work, I don't know a way around it. Will try to use a pc of a colleague tomorrow to find out if he is able to run it.

**Comment by decenergy** [comment]
Okay, tried it on a mac today and installation worked without a problem!

**Comment by decenergy** [comment]
Still problems with installing the module on a windows laptop. Tried several laptops and keep seeing the following errors: 

```
> library(devtools)
> install_github("vanatteveldt/rsyntax")
Downloading GitHub repo vanatteveldt/rsyntax@master
Installing rsyntax
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/Sander/AppData/Local/Temp/Rtmpw5U22r/devtools6ac1e6c2399/vanatteveldt-rsyntax-90db6d3"  \
  --library="C:/Program Files/R/R-3.2.3/library" --install-tests 

* installing *source* package 'rsyntax' ...
** R
** data
** preparing package for lazy loading
** help
Warning: C:/Users/Sander/AppData/Local/Temp/Rtmpw5U22r/devtools6ac1e6c2399/vanatteveldt-rsyntax-90db6d3/man/rsyntax-package.Rd:26: All text must be in a section
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error in namespaceExport(ns, exports) : 
  undefined exports: find_nodes, unique_ids
Error: loading failed
Execution halted
*** arch - x64
Error in namespaceExport(ns, exports) : 
  undefined exports: find_nodes, unique_ids
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'C:/Program Files/R/R-3.2.3/library/rsyntax'
Error: Command failed (1)
```

Any ideas what is going wrong?

**Comment by vanatteveldt** [comment]
Jan Kleinnijenhuis is having the same issue. Have you been able to figure this out?

**Comment by decenergy** [comment]
No, couldn't find a solution. Just used a macbook to do the analysis.

**Comment by vanatteveldt** [comment]
Fixed in https://github.com/vanatteveldt/rsyntax/commit/1a3e205e587d8a6dbd626e1cdf67aed969b503ab. @decenergy  If possible, could you check whether it also works for you now on Windows?

**Comment by decenergy** [comment]
Yes, it works now
