### ISSUE TITLE
Syntactic Search by Example

### ISSUE THREAD

**Issue by jwijffels** [vanatteveldt/rsyntax#10]
FYI. https://spike.wikipedia.apps.allenai.org/syntactic-search-paper.pdf

**Comment by kasperwelbers** [comment]
Thanks!

Ik denk niet dat we direct iets gaan doen met hun benadering, maar op basis van dit verhaal bedenk ik me wel dat we nu nog niet echt benadrukken dat een simpelere (non RDF) query taal ook onze voornaamste reden voor rsyntax is. Het overzicht van andere benaderingen is ook handig, want daar zitten vast nog goede ideeen tussen.
