### ISSUE TITLE
specifying OR clauses

### ISSUE THREAD

**Issue by randomgambit** [vanatteveldt/rsyntax#12]
Hi @vanatteveldt,

Here is another (hopefully) interesting example

```
mytext <- 'with package creation likely to remain soft.
myparse <- spacy_parse(mytext, nounphrase = TRUE, pos = TRUE,dependency = TRUE)
```

![image](https://user-images.githubusercontent.com/8282510/96727857-864f8780-1381-11eb-8ffb-dfdbf406374c.png)

Now lets say I am interested to pull the verb-phrases whose subject is `creation`. The usual strategy that uses the following `tquery` will not work because `creation` is actually the `children` of the ADJ parent `likely`!

```
tq <- tquery(pos = 'VERB',
             label = 'hrh', 
             rsyntax::fill(OR(pos = 'ADV', pos = 'ADJ', pos = 'AUX', pos = 'ADP', pos = 'PART', pos = 'VERB'), connected = TRUE),
             children(lemma = 'creation', label = 'h', OR( relation = 'nsubj',relation =  'nsubjpass')))

```

I can pull the verb-phrases by modifying the query as below and directly asking for children of parents:

```
tq <- tquery(pos = 'VERB',
             label = 'hrh', 
             rsyntax::fill(OR(pos = 'ADV', pos = 'ADJ', pos = 'AUX', pos = 'ADP', pos = 'PART', pos = 'VERB'), connected = TRUE),
             parents(children(lemma = 'creation', label = 'h', OR( relation = 'nsubj',relation =  'nsubjpass'))))
```

However, this is not very practical. 

Is there a way to ask for either the child is `creation` or the child of any direct parent is `creation` in one shot in `rsyntax`?

Thanks!

**Comment by kasperwelbers** [comment]
This issue is way outdated (sorry...), so I hope we at some point addressed this over mail. Assuming it's no longer relevant I'll close it.
