### ISSUE TITLE
max_curve parameter of plot_tree gets overwritten

### ISSUE THREAD

**Issue by omstuhler** [vanatteveldt/rsyntax#18]
Very minor issue but I noticed that for some sentences (usually short ones), the ```max_curve``` parameter appears to get overwritten with a larger value (probably 1?).

I dug into the function and I suspect it's something that goes on in ```rescale_var``` but I couldn't quite figure it out.

```
library(spacyr)
library(rsyntax)
spacy_initialize(model = "en_core_web_lg")
tokens = spacy_parse("The president asked him", dependency=T)
plot_tree(tokens, allign_text = T,
          max_curve = 0)

```
![download](https://user-images.githubusercontent.com/32491436/129596999-8db5cc05-2dd6-4bd4-9f69-373cbdf6e651.png)

```
tokens
doc_id sentence_id token_id     token     lemma  pos head_token_id dep_rel entity
1  text1           1        1       The       the  DET             2     det       
2  text1           1        2 president president NOUN             3   nsubj       
3  text1           1        3     asked       ask VERB             3    ROOT       
4  text1           1        4       him    -PRON- PRON             3    dobj       
```

**Comment by kasperwelbers** [comment]
Oh, good catch, thanks!

Indeed, I think that at some point I added the option to set the min/max before rescaling for another application, but then didn't specify that in this case the min should be zero. The rescale_var in this case uses the distance between nodes in calculating the curvature (only long distance nodes need curvature).

I've fixed this in the dev version.
