### ISSUE TITLE
Undeclared package ‘spacyr’ in Rd xrefs

### ISSUE THREAD

**Issue by chainsawriot** [vanatteveldt/rsyntax#21]
The package has a [check error](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/rsyntax-00check.html) (well, it is a NOTE, but CRAN considers a NOTE as an error). As many package developers got Ripleyed these days, I would suggest resolving that.

`spacyr` is referenced in the documentation of `split_UD_conj `. A simple solution is to put `spacyr` in either `Suggests` or `Enhances`. My suggestion is `Enhances` so that it won't install `spacyr` when testing. I could send a PR.

**Comment by kasperwelbers** [comment]
Thanks! don't wanna be purged. Weird that I never got this note before. Did they tighten the rules again?

Anyway, I needed to update rsyntax CRAN anyway, so I'll fix it this week. The `Enhances` solution indeed makes most sense.
