### ISSUE TITLE
CRAN version coming soon?

### ISSUE THREAD

**Issue by randomgambit** [vanatteveldt/rsyntax#4]
hello there, i was wondering if the package will be on CRAN soon?

udpipe is getting a lot of traction lately and rsyntax is a great complementary package... what do you think?

thanks!

**Comment by kasperwelbers** [comment]
Well, that's certainly the plan. I'm currently working on a paper for which I use rsyntax, so that is simultaneously serving as a test case. Hopefully I'll soon have the time to finish up!

**Comment by jwijffels** [comment]
+1 for having this on CRAN!

**Comment by kasperwelbers** [comment]
With apologies for taking so long, I'm happy to say this is now on CRAN. 

Also, I've added a mini tutorial on the github readme page for how to use this with udpipe. Originally rsyntax had the udpipe_tokenindex function, but this relied on corpustools, which seemed a bit overkill as a dependency. So now the recommended workflow is simply to run the output of udpipe through as_tokenindex.

**Comment by jwijffels** [comment]
Party!
